// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zf0lhC6RbWnTqFJeRbR7XUg6-XSTq8E',
    appId: '1:96218340172:web:38bdd8f8a3d4e0af208de9',
    messagingSenderId: '96218340172',
    projectId: 'robobrewbetaapp',
    authDomain: 'robobrewbetaapp.firebaseapp.com',
    storageBucket: 'robobrewbetaapp.firebasestorage.app',
    measurementId: 'G-DKJJB43XVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqan-ccv0ewJpRo_U3oZz8WN8-NcXAeno',
    appId: '1:96218340172:android:f3cdfb2998813e8c208de9',
    messagingSenderId: '96218340172',
    projectId: 'robobrewbetaapp',
    storageBucket: 'robobrewbetaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJX4_D_4fjgBIOxEDxfu760TR7I1_xUU4',
    appId: '1:96218340172:ios:bc2238842758bd72208de9',
    messagingSenderId: '96218340172',
    projectId: 'robobrewbetaapp',
    storageBucket: 'robobrewbetaapp.firebasestorage.app',
    iosBundleId: 'com.robobrew.coffeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJX4_D_4fjgBIOxEDxfu760TR7I1_xUU4',
    appId: '1:96218340172:ios:4fe3c602bfd7f782208de9',
    messagingSenderId: '96218340172',
    projectId: 'robobrewbetaapp',
    storageBucket: 'robobrewbetaapp.firebasestorage.app',
    iosBundleId: 'com.example.coffeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_zf0lhC6RbWnTqFJeRbR7XUg6-XSTq8E',
    appId: '1:96218340172:web:5c42c95d33938754208de9',
    messagingSenderId: '96218340172',
    projectId: 'robobrewbetaapp',
    authDomain: 'robobrewbetaapp.firebaseapp.com',
    storageBucket: 'robobrewbetaapp.firebasestorage.app',
    measurementId: 'G-W433QQQYJQ',
  );

}